server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://114.108.176.85:3307/${DB_NAME:test}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false&rewriteBatchedStatements=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:Cjve94uWhd7UWUt}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

secret:
  secret-key: ${SECRET_KEY:asdfghgfds}
  access-exp: ${ACCESS_EXP:1800000}

chatgpt:
  api-key: ${CHATGPT_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS:access}
      secret-key: ${AWS_SECRET:secret}
    region:
      static: ${AWS_REGION:ap-northeast-2}
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME:dms-terraform-state}